server.port=8001









########### Colorful console and banner off options ###########
spring.output.ansi.enabled=ALWAYS
#spring.main.banner-mode=off
########### Colorful console and banner off options ###########