













##################################### These are the two features for disabling Swagger UI. #####################################
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false
##################################### These are the two features for disabling Swagger UI. #####################################