version: '3.8'

services:
  # 1. MySQL Database Service
  mysqldb:
    image: mysql:9.7.2
    container_name: mysql_server
    environment:
      MYSQL_ROOT_PASSWORD: Admin@123
      MYSQL_DATABASE: website
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pAdmin@123"]
      interval: 5s
      timeout: 5s
      retries: 10

  # 2. Spring Boot Application Service
  backend-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-container
    ports:
      - "8080:8080"
    depends_on:
      mysqldb:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/website?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Admin@123

volumes:
  mysql_data: