version: '3.8'

services:
  # 1. MySQL Database Service
  mysqldb:
    image: mysql:8.0
    container_name: mysql_server
    environment:
      MYSQL_ROOT_PASSWORD: Admin@123
      MYSQL_DATABASE: website
      MYSQL_USER: root
      MYSQL_PASSWORD: Admin@123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # 2. Spring Boot Application Service
  backend-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot_app
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/website?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Admin@123

volumes:
  mysql_data: